[pytest]
#bdd_features_base_dir = tests/features

testpaths = tests
python_files = test_*.py
python_functions = test_*

addopts = 
        #--full-trace
        --gherkin-terminal-reporter -v
        #--html=report.html --self-contained-html
        --alluredir=allure-results -v
        -n 4

markers = [
    
    regression: mark tests as regression tests
    login: mark tests as login tests
    positive: mark tests as positive tests
    negative: mark tests as negative tests
 
    ]